### ISSUE TITLE
ValueError: File object has no read() method, or readable() returned False.

### ISSUE THREAD

**Issue by ItsGifNotJif** [hkchengrex/MMAudio#94]
Running into ValueError whenever trying to use Video-to-Audio generation.
Using MMAudio installed from Pinokio, but the error is the same regardless if using it from browser Gradio interface, or in Pinokio.

Getting these errors:

  File "C:\pinokio\api\MMAudio.git\app\env\lib\site-packages\gradio\queueing.py", line 763, in process_events
    response = await route_utils.call_process_api(
  File "C:\pinokio\api\MMAudio.git\app\env\lib\site-packages\gradio\route_utils.py", line 354, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\pinokio\api\MMAudio.git\app\env\lib\site-packages\gradio\blocks.py", line 2106, in process_api
    result = await self.call_function(
  File "C:\pinokio\api\MMAudio.git\app\env\lib\site-packages\gradio\blocks.py", line 1588, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\pinokio\api\MMAudio.git\app\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\pinokio\api\MMAudio.git\app\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2485, in run_sync_in_worker_thread    
    return await future
  File "C:\pinokio\api\MMAudio.git\app\env\lib\site-packages\anyio\_backends\_asyncio.py", line 976, in run
    result = context.run(func, *args)
  File "C:\pinokio\api\MMAudio.git\app\env\lib\site-packages\gradio\utils.py", line 1048, in wrapper
    response = f(*args, **kwargs)
  File "C:\pinokio\api\MMAudio.git\app\env\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "C:\pinokio\api\MMAudio.git\app\gradio_demo.py", line 72, in video_to_audio
    video_info = load_video(video, duration)
  File "C:\pinokio\api\MMAudio.git\app\mmaudio\eval_utils.py", line 184, in load_video
    output_frames, all_frames, orig_fps = read_frames(video_path,
  File "C:\pinokio\api\MMAudio.git\app\mmaudio\data\av_utils.py", line 63, in read_frames
    with av.open(video_path) as container:
  File "av/container/core.pyx", line 482, in av.container.core.open
  File "av/container/core.pyx", line 279, in av.container.core.Container.__cinit__
  File "av/container/pyio.pyx", line 41, in av.container.pyio.PyIOFile.__cinit__
ValueError: File object has no read() method, or readable() returned False

based on suggestion in previous thread on this issue, av has been updated with pip install av --upgrade, but nothing changed. Current av version is 16.0.1

**Comment by hkchengrex** [comment]
Thanks for the hint! It should be fixed with 0537b9a4f00cd9b1b26d77ee93da3c930a7177e5. Feel free to re-open if there are still issues.

**Comment by 6Morpheus6** [comment]
Thank you @hkchengrex 
The error is in deed gone. But MMaudio is much slower now. We noticed this behavior also with other apps like MatAnyone and DDColor.
The generation times are insane.
The seagull example video in MMAudio needed less than 10 secs with gradio<6 (RTX5080)
Now with gradio 6.0.1 it's at 480 sec and still generating...

<img width="3840" height="2160" alt="Image" src="https://github.com/user-attachments/assets/98d44fd4-5fed-47f2-95b6-055496875118" />


The only indicator we have is this Traceback error in MMAudio (the same one like in MatAnyone)

<img width="1486" height="346" alt="Image" src="https://github.com/user-attachments/assets/c8826fb9-b334-4725-8714-5207313a31ef" />

The error comes from gradio. My GPU is being utilized. The right torch version is installed.

<img width="3840" height="2160" alt="Image" src="https://github.com/user-attachments/assets/5049dc61-2d72-4ad8-8aa0-dd4631521624" />

PS: I do not have the permission to reopen this issue.

**Comment by ItsGifNotJif** [comment]
The CUDA issue persists in other versions of MMaudio based on this project too, especially ones where Gradio is pinned to 5.50.0. I'm not a programmer so no clue what is happening ,but generation times are very long (talking like 500 seconds to generate 5 seconds of content) and despite double checking that CUDA is installed and is in fact detected, it's not utilized at all. Testing on RTX4060 I've ran into the same problem across all MMAudio derivatives I've tried.
Also not sure if this is relevenat to this specific project, but one of the MMAudio forks I've ran throws this error. May be relevenat, maybe not, maybe someone who actually understands this thing can glance at it and get something out of it.

<img width="1032" height="177" alt="Image" src="https://github.com/user-attachments/assets/93cf16e0-ad9d-45f9-9984-563d653d5d1c" />
